# Generated by Django 6.0.4 on 2026-05-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_remove_billing_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
